version: '2'
services:
    csr-app:
        image: csr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://csr-mariadb:3306/csr
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    csr-mariadb:
        extends:
            file: mariadb.yml
            service: csr-mariadb
